### ISSUE TITLE
Update code

### ISSUE THREAD

**Issue by martinszy** [diegodlh/unofficial-hypothesis-extension#13] opened 2022-01-25 16:21 UTC
This thread explains that some sites have problems with older versions https://github.com/hypothesis/product-backlog/issues/1146#issuecomment-1021311862

Please update.

Thanks.

**Comment by diegodlh** [comment] 2022-01-25 18:11
Thanks for reporting this. This is a known bug; see #11.

Updating the client is not trivial, because some changes have been made which conflict with the changes I made to support some of this unofficial extension's features. Unfortunately, I'm not having the time lately to take care of this. Hopefully I will in the future.

In the meantime, there is a (nonperfect) workaround described in #11.

Closing this as duplicate of #11.

**Closed as completed by diegodlh** 2022-01-25 18:11 UTC
